language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    allow_failures:
        - php: 7.0
        - php: 7.4
    fast_finish: true

before_script:
    - composer self-update
    - composer require php-coveralls/php-coveralls

after_success:
    - bash <(curl -s https://codecov.io/bash)
  
script: 
    - phpunit --coverage-clover=coverage.xml
